### ISSUE TITLE
Reactive app blocking errors

### ISSUE THREAD

**Issue by petr24** [peerlibrary/meteor-reactive-publish#13]
Hey man, 

Great work on this package, just wanted to see if anyone else is starting to experience this issue. 

Here is a log that I started to get often, and it never used to happen, but now it does for some reason. 
I removed kadira packages, saw on another issue that was causing some problems. 

The kadira packages I currently have.
kadira:blaze-layout
kadira:debug
kadira:flow-router 

And when the error triggers, it feels random, I will edit/save the document and out of nowhere the log shows up and the document is gone from the client. 

Here is a log of the issue. 

```
Exception from sub sharedContacts id uMwMrYeBBkdJTARhH { stack: 'TypeError: Can\'t call method on
null\n    at TypeError (<anonymous>)\n    at module.exports
(/Users/pchubenko/.meteor/packages/ecmascript
runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript
runtime/node_modules/core-js/modules/$.defined.js:3:28)\n    at module.exports
(/Users/pchubenko/.meteor/packages/ecmascript
runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript
runtime/node_modules/core-js/modules/$.to-object.js:4:17)\n    at Function.keys
(/Users/pchubenko/.meteor/packages/ecmascript
runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript
runtime/node_modules/core-js/modules/es6.object.keys.js:6:18)\n    at [object Object].cursorProto
(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:138:1)\n    at [object
Object].kadira_Cursor_observeChanges [as observeChanges] 
packages/meteorhacks_kadira/lib/hijack/set_labels.js:87:1)\n    at
Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:312:1)\n    at [object
Object].Cursor._publishCursor (packages/mongo/mongo_driver.js:892:1)\n    at publishHandlerResult
(packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:34:1)\n    at
Computation.<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive
publish.js:326:1)',
```

And this is how my pub/sub looks

``` javascript
Meteor.publish("sharedContacts", function () {
    this.autorun(function (computation) {
        var allSharedContacts = SharedContacts.find({sharedWith: this.userId, accepted: true}).fetch();
        return ContactData.find({_id: {$in: _.pluck(allSharedContacts, 'contactId')}, shared: true});
    });
});

```

Sub is at the router in lib directory

``` javascript
FlowRouter.subscriptions = function() {
    this.register('sharedContacts', Meteor.subscribe('sharedContacts'));
};
```

I also tried doing sub at the Template level, the error from sub looks like this.

```
 Exception from Tracker recompute function:
 TypeError: Can't call method on  null
     at TypeError (<anonymous>)
     at module.exports (/Users/pchubenko/.meteor/packages/ecmascript-runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.defined.js:3:28)
     at module.exports (/Users/pchubenko/.meteor/packages/ecmascript-runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.to-object.js:4:17)
     at Function.keys (/Users/pchubenko/.meteor/packages/ecmascript-runtime/.0.2.6.gitom7++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.object.keys.js:6:18)
     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:138:1)
     at [object Object].kadira_Cursor_observeChanges [as observeChanges] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:87:1)
     at [object Object].MeteorCursor._depend (packages/peerlibrary_reactive-mongo/packages/peerlibrary_reactive-mongo.js:46:1)
     at [object Object].MeteorCursor.(anonymous function) (packages/peerlibrary_reactive-mongo/packages/peerlibrary_reactive-mongo.js:71:1)
     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
     at [object Object].kadira_Cursor_fetch [as fetch] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:75:1)
```

**Comment by mitar** [comment]
> I removed kadira packages, saw on another issue that was causing some problems. 

Only server-side kadira package is a problem. Not Blaze/layout/router ones.

```
     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:138:1)
```

Yes, this looks exactly the same issue as #7.
