### ISSUE TITLE
Testing with reactive-publish package

### ISSUE THREAD

**Issue by tpasque** [peerlibrary/meteor-reactive-publish#19]
What is the best way to do publication testing with Meteor 1.3?

We are working with a publication test based on the Meteor docs, and they recommend using PublicationCollector, but it isn't working for us.  Here is the error in my terminal:

Exception in queued task: TypeError: Cannot call method 'idStringify' of undefined 
at PublicationCollector.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1) 
at added (packages/mongo/collection.js:346:11)
at packages/mongo/observe_multiplex.js:183:30
at Function..each..forEach (packages/underscore/underscore.js:108:1)
at Object.task (packages/mongo/observe_multiplex.js:177:9)
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
at packages/meteor/fiber_helpers.js:125:1

Thank you

**Comment by mitar** [comment]
I use TinyTest for testing with [this wrapper](https://github.com/peerlibrary/meteor-classy-test).

Not sure what that package is doing to break this package.

**Comment by hexsprite** [comment]
I submitted a fix for this https://github.com/johanbrook/meteor-publication-collector/pull/10

**Comment by mitar** [comment]
Fixed in the above pull request. Thanks!
