### ISSUE TITLE
App with Flow Router requires page reload to publish

### ISSUE THREAD

**Issue by ajschmaltz** [peerlibrary/meteor-reactive-publish#24]
So, I have a subscription on my client...

`Meteor.subscribe('posts');`

and a publish on my server...

```
Meteor.publish('posts', function () {
    this.autorun(function (computation) {
        var author = Authors.findOne({userId: this.userId});
        return Posts.find({authorId: author._id});
    });
});
```

But, it doesn't return any post unless I reload the page in the browser.

**Comment by mitar** [comment]
Please make a small reproduction. This package is used in production in many apps, so it is probably an error on your side.

**Comment by ajschmaltz** [comment]
Ok, I created an entire app to reproduce it.  What I found is the behavior only started once I added flow router.  I don't know how to share the code besides posting it here, so I'll do that.

Keep in mind, this isn't the use case, I'm not using posts and authors, but it best demonstrates.

First, create a meteor app and add these packages:

- peerlibrary:reactive-publish
- accounts-password
- accounts-ui
- kadira:flow-router
- kadira:blaze-layout

javascript
```
var Posts = new Mongo.Collection('posts');
var Authors = new Mongo.Collection('authors');
if (Meteor.isServer) {
    Meteor.publish('posts', function () {
        this.autorun(function (computation) {
            var author = Authors.findOne({userId: this.userId});
            console.log(author._id);
            console.log(Posts.find({}).fetch());
            return Posts.find({authorId: author._id});
        });
    });
}
if (Meteor.isClient) {
    FlowRouter.route('/', {
        action: function(params, queryParams) {
            BlazeLayout.render('create');
        }
    });
    FlowRouter.route('/posts', {
        action: function(params, queryParams) {
            BlazeLayout.render('posts');
        }
    });
    Meteor.subscribe('posts');
    Template.create.onCreated(function() {
       this.authorId = new ReactiveVar(null);
    });
    Template.posts.helpers({
       posts: function(){
           return Posts.find({});
       }
    });
    Template.create.helpers({
        authorId: function() {
            return Template.instance().authorId.get();
        }
    })
    Template.create.events({
       'submit #authorForm': function(event, instance) {
           event.preventDefault();
           var author = event.target.author.value;
           instance.authorId.set(Authors.insert({
              userId: Meteor.userId(),
               author: author
           }));

       },
        'submit #postForm': function(event, instance) {
            event.preventDefault();
            var post = event.target.post.value;
            Posts.insert({
               authorId: instance.authorId.get(),
                post: post
            });
        }
    });
}
```

and here's the html

```
<body>
<h2>Follow these steps</h2>
<ul>
    <li>Login</li>
    <li>fill out the first text box and hit enter</li>
    <li>fill out the second text box and hit enter</li>
    <li>click posts</li>
    <li>reload the page</li>
</ul>
</body>
<template name="create">
    {{> loginButtons}}
    {{#if currentUser}}
        <form id="authorForm">
            <input type="text" id="author" name="author" placeholder="type anything & enter"/>
        </form>
        {{#if authorId}}
            <form id="postForm">
                <input type="text" id="post" name="post" placeholder="type anything & enter" />
            </form>
        {{/if}}
    {{/if}}
    <a href="/posts">Posts</a>
</template>
<template name="posts">
    {{#each posts}}
        {{post}}
    {{/each}}
    <a href="/">Create</a>
</template>
```

**Comment by mitar** [comment]
Can you create a repo with this code?

**Comment by ajschmaltz** [comment]
I think I figured out how to do that ....

https://github.com/ajschmaltz/rapdemo

**Comment by mitar** [comment]
When you run it, you can see the error in the console log:

```
I20161128-20:18:41.799(-8)? Exception from sub posts id ik3GyeAznv7q3g8N2 TypeError: Cannot read property '_id' of undefined
I20161128-20:18:41.799(-8)?     at Subscription.<anonymous> (everything.js:7:25)
I20161128-20:18:41.799(-8)?     at Computation.<anonymous> (packages/peerlibrary_reactive-publish.js:337:26)
I20161128-20:18:41.800(-8)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20161128-20:18:41.800(-8)?     at packages/meteor.js:1189:14
I20161128-20:18:41.800(-8)?     at packages/peerlibrary_server-autorun.js:469:23
I20161128-20:18:41.800(-8)?     at packages/peerlibrary_server-autorun.js:447:18
I20161128-20:18:41.800(-8)?     at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils.js:183:12)
I20161128-20:18:41.801(-8)?     at Computation.Tracker.Computation.Computation._runInside (packages/peerlibrary_server-autorun.js:436:23)
I20161128-20:18:41.801(-8)?     at packages/peerlibrary_server-autorun.js:461:22
I20161128-20:18:41.801(-8)?     at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils.js:183:12)
```

I think this might tell you where you have a bug in your code. Hint: when you are not logged in, `this.userId` is null, so `Authors.findOne` returns null, so `author._id` fails.

**Comment by ajschmaltz** [comment]
ok, I thought that it would rerun after the userid was populated.  a quick if and it works fine.  I can't believe I didn't catch this...  Thank you!
