### ISSUE TITLE
Error: Removed non-existent document

### ISSUE THREAD

**Issue by ramezrafla** [peerlibrary/meteor-reactive-publish#25]
When removing a doc while using redis-oplog, or removing a doc from the DB externally to meteor (e.g. mongoclient or robomongo) we get the error:

```
Exception in queued task: Error: Removed nonexistent document f9fQjuKsW2JdA65Zs
I20170202-00:26:50.319(-5)?     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
I20170202-00:26:50.319(-5)?     at Session.removed (packages/ddp-server/livedata_server.js:391:10)
I20170202-00:26:50.322(-5)?     at Subscription.removed (packages/ddp-server/livedata_server.js:1273:19)
I20170202-00:26:50.323(-5)?     at removed (packages/mongo/collection.js:352:11)
I20170202-00:26:50.323(-5)?     at callbacks.(anonymous function) (packages/peerlibrary_reactive-publish/server.coffee:36:24)
I20170202-00:26:50.324(-5)?     at packages/mongo/observe_multiplex.js:183:30
I20170202-00:26:50.325(-5)?     at Array.forEach (native)
I20170202-00:26:50.325(-5)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20170202-00:26:50.325(-5)?     at Object.task (packages/mongo/observe_multiplex.js:177:9)
I20170202-00:26:50.325(-5)?     at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170202-00:26:50.326(-5)?     at packages/meteor.js:785:14
```

**Comment by mitar** [comment]
Hm, can you make a small reproduction using [directcollection](https://github.com/peerlibrary/meteor-directcollection) which is a direct connection to Mongo.

I am unsure why would this happen though with this package. Really strange. I do not know that it would rely on changes coming from inside.

**Comment by ramezrafla** [comment]
Thanks @mitar, so you want me to (a) replace the mongo collection in the reactive publish with the directcollection or (b) have meteor make the change with directcollection and see how the reactive publish behaves?

As mentioned above, I faced the same issue with redis-oplog (issue raised but I volunteered to get to the bottom of it).

**Comment by mitar** [comment]
(b). So direct collection directly changes the Mongo. I am curious if you can replicate with that. Then we know that there is nothing fancy with redis-oplog integration (or hooking machinsm) or something like that.

**Comment by ramezrafla** [comment]
Ok, but this is similar to what I did already. I altered the DB externally to my app using **mongoclient** [Edit: fixed app name] (running as an external app, so for all practical purposes, independent from the app we are testing), and the reactive publish triggered this error. Not using redis-oplog at the moment, just wanted to highlight that we face the same issue there.

**Comment by ramezrafla** [comment]
Ok, so we found what was going on (at least I believe we do). We had in our reactive publish a reactive find which contained extra fields, that seemed to trigger reruns of the publish -- looks like a race condition. 

What is odd is that line 36 in server.coffee is within a `try`, yet triggers an error.

I'll go ahead and close this so not to litter, but it's something that could cause issues with redis-oplog. I'll investigate and revert if need be.

Thanks @mitar for your continued courtesy.

**Comment by mitar** [comment]
Yes, I wanted to have a reproduction without redis-oplog, and a command from inside which changes the meteor so that I could investigate. I understand that this is probably the same as changing it manually. But it is good to have it in a code because it then possible to create a test to test in the future.

**Comment by mitar** [comment]
> What is odd is that line 36 in server.coffee is within a try, yet triggers an error.

Sometimes I realized that numbers do not match always. All this preprocesing of CoffeeScript/JavaScript can move things around and make lines wrong.

But still, why would extra fields throw such an error?

**Comment by ramezrafla** [comment]
> But still, why would extra fields throw such an error?

The only unscientific reason I can think of is a race condition somewhere, that causes the reactive publishing to be triggered twice (or more), with the second call failing.

> I wanted to have a reproduction without redis-oplog, and a command from inside which changes the meteor so that I could investigate.

Understood. It's high on our to-do's as are supporting @theodorDiaconu in getting redis-oplog to work with reactive publishing. I'll work on getting you a test repo.

**Comment by mitar** [comment]
Has this ever be resolved? @theodorDiaconu?

**Comment by theodorDiaconu** [comment]
@mitar not yet :(

**Comment by mitar** [comment]
So is this error still happening?

**Comment by mitar** [comment]
Closing because of no activity.
