### ISSUE TITLE
ReferenceError: ReactiveVar is not defined

### ISSUE THREAD

**Issue by butlera1** [peerlibrary/meteor-reactive-publish#53]
Performed `meteor add peerlibrary:reactive-publish` then ran application and server side throws the following error:

`W20220203-16:56:21.528(-7)? (STDERR) Debugger attached.
W20220203-16:56:25.604(-7)? (STDERR) Waiting for the debugger to disconnect...
W20220203-16:56:25.619(-7)? (STDERR) /Users/butlea1/.meteor/packages/meteor-tool/.2.5.3.1ssl86p.p3e7++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20220203-16:56:25.619(-7)? (STDERR) 						throw(ex);
W20220203-16:56:25.619(-7)? (STDERR) 						^
W20220203-16:56:25.619(-7)? (STDERR) 
W20220203-16:56:25.619(-7)? (STDERR) ReferenceError: ReactiveVar is not defined
W20220203-16:56:25.620(-7)? (STDERR)     at _fn (packages/peerlibrary_reactive-publish.js:421:5)
W20220203-16:56:25.620(-7)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1501:3
W20220203-16:56:25.620(-7)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1506:4
W20220203-16:56:25.620(-7)? (STDERR)     at packages/peerlibrary_reactive-publish.js:1512:3
W20220203-16:56:25.620(-7)? (STDERR)     at /Users/butlea1/Code/turboflowSystem/turboflow/.meteor/local/build/programs/server/boot.js:406:15
W20220203-16:56:25.620(-7)? (STDERR)     at Array.forEach (<anonymous>)
W20220203-16:56:25.620(-7)? (STDERR)     at /Users/butlea1/Code/turboflowSystem/turboflow/.meteor/local/build/programs/server/boot.js:405:11
W20220203-16:56:25.621(-7)? (STDERR)     at /Users/butlea1/Code/turboflowSystem/turboflow/.meteor/local/build/programs/server/boot.js:464:7
W20220203-16:56:25.621(-7)? (STDERR)     at Function.run (/Users/butlea1/Code/turboflowSystem/turboflow/.meteor/local/build/programs/server/profile.js:280:14)
W20220203-16:56:25.621(-7)? (STDERR)     at /Users/butlea1/Code/turboflowSystem/turboflow/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
`

Performed `meteor add reactive-var` and problem persists.

Performed `meteor remove peerlibrary:reactive-publish` and build ran correctly.

I'm running with Meteor version 2.5.3.

Any thoughts on the issue?

--Arch

**Comment by mitar** [comment]
This has been reported in the past:
* https://github.com/peerlibrary/meteor-reactive-publish/issues/21
* https://github.com/peerlibrary/meteor-reactive-publish/issues/44#issuecomment-533425160

I am not completely sure where it comes from, because only tests are using reactive vars.

**Comment by nooitaf** [comment]
For me it was another ancient package depending on `comsos:browserify` which clamped coffescript down to the 1.0.6 version. 
```
   Constraints on package "coffeescript":
   * coffeescript@1.0.6 <- cosmos:browserify 0.5.1 <- djedi:sanitize-html-client 1.11.3
```

That package isn't even needed anymore since Meteor 1.4, so after some cleanup and using the `sanitize-html` npm package directly, it all worked fine :)
